# Build image for the 'Library in a box' 
FROM ubuntu:14.04
MAINTAINER philip wang <philip.wj@gmail.com>

# install python-software-properties which is the dependency to run add-apt-repository
RUN apt-get update && apt-get -y upgrade
# RUN apt-get -y install python-software-properties 
RUN apt-get -y install software-properties-common

# Install Oracle JDK 7
RUN add-apt-repository ppa:webupd8team/java
RUN apt-get update
RUN apt-get -y upgrade
# Accept Oracel license automatically
RUN echo oracle-java7-installer shared/accepted-oracle-license-v1-1 select true | /usr/bin/debconf-set-selections
RUN apt-get -y install oracle-java7-installer 
# Set Java environment variables
RUN apt-get install oracle-java7-set-default
RUN update-java-alternatives -s java-7-oracle

# Verify Java Version
RUN java -version
